apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace }}
data:
{{ $root := . }}
{{ range $path, $bytes := .Files.Glob "conf/*" }}
{{ base $path | indent 2 }}: |-
{{ tpl ( $root.Files.Get $path ) $ | indent 4 }}
{{ end }}
