---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: {{ .Values.service.containerPort }}
      targetPort: {{ .Values.service.servicePort }}
      nodePort: {{ .Values.service.nodePort }}
  selector:
    k8s-app: {{ .Values.service.name }}
